[2021-10-09 04:12:21,452] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: template_dag.generate_new_logs 2021-10-09T04:12:17.851997+00:00 [queued]>
[2021-10-09 04:12:21,461] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: template_dag.generate_new_logs 2021-10-09T04:12:17.851997+00:00 [queued]>
[2021-10-09 04:12:21,461] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2021-10-09 04:12:21,461] {taskinstance.py:1095} INFO - Starting attempt 1 of 2
[2021-10-09 04:12:21,461] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2021-10-09 04:12:21,474] {taskinstance.py:1114} INFO - Executing <Task(BashOperator): generate_new_logs> on 2021-10-09T04:12:17.851997+00:00
[2021-10-09 04:12:21,478] {standard_task_runner.py:52} INFO - Started process 415 to run task
[2021-10-09 04:12:21,482] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'template_dag', 'generate_new_logs', '2021-10-09T04:12:17.851997+00:00', '--job-id', '326', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/template_dag.py', '--cfg-path', '/tmp/tmpelmfkb4s', '--error-file', '/tmp/tmpp4hstb_2']
[2021-10-09 04:12:21,482] {standard_task_runner.py:77} INFO - Job 326: Subtask generate_new_logs
[2021-10-09 04:12:21,519] {logging_mixin.py:109} INFO - Running <TaskInstance: template_dag.generate_new_logs 2021-10-09T04:12:17.851997+00:00 [running]> on host a6cf1bcf3ec3
[2021-10-09 04:12:21,619] {taskinstance.py:1251} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=youremail@host.com
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=template_dag
AIRFLOW_CTX_TASK_ID=generate_new_logs
AIRFLOW_CTX_EXECUTION_DATE=2021-10-09T04:12:17.851997+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-10-09T04:12:17.851997+00:00
[2021-10-09 04:12:21,619] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-10-09 04:12:21,620] {subprocess.py:63} INFO - Running command: ['bash', '-c', '#!/bin/bash\n\n# This script creates a log named filename  at DEST_PATH using macros, variables\n# and templating from Airflow\n\n# DEST_PATH corresponds to the destination path where the log file is going to be created\n# Notice that DEST_PATH is created using templating, macros and variables with AIRFLOW\n# var.value.source_path is a variable coming from the Airflow UI -> variables panel\n# macros.ds_format() is a macro defined by Airflow\n# ts_nodash is a variable defined by Airflow\n# curly brackets allow to use Jinja Templating to replace placeholders with values at runtime\nDEST_PATH=/home/duyvan/Downloads/duy_airflow_local/3.8/dags/data/2021-10-09-04-12\n\nmkdir -p $DEST_PATH\necho "index;message;timestamp;ds_airflow" >> $DEST_PATH/log.csv\necho $(whoami)\nfor i in {1..5}\ndo\n    RANDOM_STRING=$(cat /dev/urandom | tr -dc \'a-zA-Z0-9\' | fold -w 32 | head -n 1)\n    CURRENT_TS=$(date +%s)\n    # We template the variable ds in order to have the current executation date of the DAG\n    # filename is given from the parameter params of the BashOperator\n    echo "$i;$RANDOM_STRING;$CURRENT_TS;2021-10-09" >> $DEST_PATH/log.csv\ndone']
[2021-10-09 04:12:21,627] {subprocess.py:74} INFO - Output:
[2021-10-09 04:12:21,631] {subprocess.py:78} INFO - mkdir: cannot create directory ‘/home/duyvan’: Permission denied
[2021-10-09 04:12:21,631] {subprocess.py:78} INFO - bash: line 14: /home/duyvan/Downloads/duy_airflow_local/3.8/dags/data/2021-10-09-04-12/log.csv: No such file or directory
[2021-10-09 04:12:21,633] {subprocess.py:78} INFO - airflow
[2021-10-09 04:12:21,641] {subprocess.py:78} INFO - bash: line 22: /home/duyvan/Downloads/duy_airflow_local/3.8/dags/data/2021-10-09-04-12/log.csv: No such file or directory
[2021-10-09 04:12:21,648] {subprocess.py:78} INFO - bash: line 22: /home/duyvan/Downloads/duy_airflow_local/3.8/dags/data/2021-10-09-04-12/log.csv: No such file or directory
[2021-10-09 04:12:21,655] {subprocess.py:78} INFO - bash: line 22: /home/duyvan/Downloads/duy_airflow_local/3.8/dags/data/2021-10-09-04-12/log.csv: No such file or directory
[2021-10-09 04:12:21,661] {subprocess.py:78} INFO - bash: line 22: /home/duyvan/Downloads/duy_airflow_local/3.8/dags/data/2021-10-09-04-12/log.csv: No such file or directory
[2021-10-09 04:12:21,668] {subprocess.py:78} INFO - bash: line 22: /home/duyvan/Downloads/duy_airflow_local/3.8/dags/data/2021-10-09-04-12/log.csv: No such file or directory
[2021-10-09 04:12:21,669] {subprocess.py:82} INFO - Command exited with return code 1
[2021-10-09 04:12:21,679] {taskinstance.py:1462} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/taskinstance.py", line 1164, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/taskinstance.py", line 1282, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/taskinstance.py", line 1312, in _execute_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/bash.py", line 176, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-10-09 04:12:21,681] {taskinstance.py:1505} INFO - Marking task as UP_FOR_RETRY. dag_id=template_dag, task_id=generate_new_logs, execution_date=20211009T041217, start_date=20211009T041221, end_date=20211009T041221
[2021-10-09 04:12:21,733] {local_task_job.py:151} INFO - Task exited with return code 1
[2021-10-09 04:12:21,758] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
